
replicaCount: 1

image:
  repository: 13.48.106.244/smart-task-management-system/report-service
  tag: "23"
  pullPolicy: Always

imagePullSecrets: []

service:
  type: ClusterIP
  port: 5004
  targetPort: 5004

containerPort: 5004

resources: {}

env:
  PORT: "5004"
  JWT_SECRET: "mysecretkey"
  MONGO_URI: "mongodb://mongodb:27017/taskdb"

ingress:
  enabled: true
  className: nginx

  host: report.smarttask.local

  path: /

  pathType: Prefix
