apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "notification-service.fullname" . }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "notification-service.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "notification-service.selectorLabels" . | nindent 8 }}

    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}

      containers:
      - name: notification-service

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.containerPort }}

        env:
        - name: PORT
          value: "{{ .Values.env.PORT }}"

        - name: JWT_SECRET
          value: "{{ .Values.env.JWT_SECRET }}"

        - name: MONGO_URI
          value: "{{ .Values.env.MONGO_URI }}"

        resources:
          {{- toYaml .Values.resources | nindent 10 }}