route:
  receiver: slack
receivers:
- name: slack
  slack_configs:
  - api_url: https://hooks.slack.com/services/REPLACE/ME
    channel: '#alerts'
- name: email
  email_configs:
  - to: devops@example.com
