apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    release: kube-prometheus-stack

spec:
  selector:
    matchLabels:
      {{- include "api-gateway.selectorLabels" . | nindent 6 }}

  namespaceSelector:
    matchNames:
      - smart-task

  endpoints:
    - port: http
      path: /metrics
      interval: 15s


