replicaCount: 1

image:
  repository: 13.48.106.244/smart-task-management-system/task-service
  tag: "23"
  pullPolicy: Always

imagePullSecrets: []

service:
  type: ClusterIP
  port: 5002
  targetPort: 5002

containerPort: 5002

resources: {}

env:
  PORT: "5002"
  JWT_SECRET: "mysecretkey"
  MONGO_URI: "mongodb://mongodb:27017/taskdb"

ingress:
  enabled: true
  className: nginx

  host: task.smarttask.local

  path: /

  pathType: Prefix
